version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    REPOSITORY_NAME: adarshecr
    REPOSITORY_URI: 864899829058.dkr.ecr.us-east-1.amazonaws.com/adarshecr

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - aws --version
      - echo "Checking if ECR repository exists..."
      - >
        if ! aws ecr describe-repositories --repository-names "$REPOSITORY_NAME" --region "$AWS_DEFAULT_REGION" > /dev/null 2>&1; then
          echo "Repository does not exist. Creating...";
          aws ecr create-repository --repository-name "$REPOSITORY_NAME" --region "$AWS_DEFAULT_REGION";
        else
          echo "Repository exists.";
        fi
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REPOSITORY_URI"
      - echo "Setting image tag..."
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest} | cut -c 1-7)
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Starting build phase..."
      - docker build -t "$REPOSITORY_URI:$IMAGE_TAG" .
      - docker tag "$REPOSITORY_URI:$IMAGE_TAG" "$REPOSITORY_URI:latest"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - docker push "$REPOSITORY_URI:$IMAGE_TAG"
      - docker push "$REPOSITORY_URI:latest"
      - echo "Creating imagedefinitions.json file..."
      - printf '[{"name":"fargate-container","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

